const String home = '/home';
const String addEmployee = '/addEmployee';
const String employeeScreen = '/employeeScreen';
const String inconingOutGoingScreen = '/inconingOutGoingScreen';
const String addIncomingOutGoing = '/addIncomingOutGoing';
const String ordersScreen = '/ordersScreen';
const String addOrdersScreen = '/addOrdersScreen';
const String salaryScreen = '/salaryScreen';
const String addSalaryScreen = '/addSalaryScreen';
const String exchangeMoneyScreen = '/exchangeMoneyScreen';
const String userScreen = 'userScreen';
const String addExchangeMoneyScreen = '/addExchangeMoneyScreen';
const String addUserScreen = '/addUserScreen';
const String settingScreen = '/setting_screen';
const String reportScreen = '/reportScreen';
const String carScreen = '/carScreen';
// android
const String apiRoute = "http://10.0.2.2:8000/api/v1/";
// const String apiRoute = "http://127.0.0.1:8000/api/v1/";
